### ISSUE TITLE
Feature: add unlit soul torch

### ISSUE THREAD

**Issue by legosteenjaap** [realguyman/totally_lit#2]

**Comment by realguyman** [comment]
I'm thinking I can replace Minecraft's soul torch recipe to craft an unlit variant. By default soul torches will be more resistant to water and last an infinite amount of time. It'd make sense to have a campfire recipe for it, too.

**Comment by Andrew6rant** [comment]
If you do decide to add Unlit Soul Torches, I think it would be very cool to also make mob death be a trigger that lights them
