### ISSUE TITLE
Lighting unlit lantern with flint & steel waterlogs it

### ISSUE THREAD

**Issue by isthisrad** [realguyman/totally_lit#31]
While the unlit lantern does turn into a lit lantern, it also waterlogs the block consistently. Water begins flowing after some time. On 0.11.0 1.19+.

**Comment by realguyman** [comment]
Thanks! I'll check this out soon.

**Comment by realguyman** [comment]
I've not been able to reproduce the bug. Please attach a log file. More likely to be a mod conflict issue.
