### ISSUE TITLE
Unlit Torches Not Dropping

### ISSUE THREAD

**Issue by MinecraftGuy926** [realguyman/totally_lit#33]
Is this a bug or intended? 0.13.2

**Comment by realguyman** [comment]
Could you give more context? This is not intended. Unlit torches should drop.

**Comment by realguyman** [comment]
I found the [responsible commit](https://github.com/realguyman/totally_lit/commit/f8a4b99f7218f8969d32a7b58c1dc11103d836c7) for the issue. It appears calling the `dropsLike` method _before_ registering the block supplied to the `source` block causes issues.

**Comment by realguyman** [comment]
Fixed as of https://github.com/realguyman/totally_lit/commit/bf6f279ebc6618f0e0d2a88aa3b9e88ba569cc6b. Will be available in the next release.
