### ISSUE TITLE
[Suggestion] Configuration for torches burn out into redstone torches 

### ISSUE THREAD

**Issue by Arsoth** [realguyman/totally_lit#39]
I don't think it would be game breaking, but could be very neat if regular torches on burn out turned into redstone torches, essentially "smouldering" so you could still see them in the dark and have a small mostly useless amount of light, and they could be relit back into regular torches.

Technically this could allow you to get redstone torches early game, but without redstone in of itself to make contraptions I don't think that would affect much.

**Comment by realguyman** [comment]
Changing an unlit torch to a redstone torch is not lore-friendly. I have no interest in implementing this. If you want a smouldering torch variant, please open a new issue!
