### ISSUE TITLE
Suggestion: make it possible for torches to be placed underwater, but make them instantly convert into unlit torches

### ISSUE THREAD

**Issue by legosteenjaap** [realguyman/totally_lit#7]

**Comment by realguyman** [comment]
Minecraft's torches are immediately broken, and upon that breakage Totally Lit will transform the floating item into an unlit variant. It's not within the scope of this to make Minecraft's torches waterloggable.

I can add support for mods that _do_ make Minecraft's torches waterloggable, though.
