### ISSUE TITLE
Bug: 1.18.2 Torch duplication

### ISSUE THREAD

**Issue by bad-badger** [realguyman/totally_lit#8]
When going underwater while holding one or more lit torches in the off hand slot, the torches remain lit, and an equal number of unlit torches are added to your inventory.

So for example, if I go underwater while holding 5 lit torches in my offhand, the 5 torches remain lit, but now 5 new unlit torches are added to my inventory.

**Comment by realguyman** [comment]
Thanks for reporting this bug. I should have this fixed by Saturday. Apparently I have to manually handle the player's off hand instead of just the inventory. Which isn't necessarily hard, just tedious.

**Comment by bad-badger** [comment]
Ok, that makes sense. It seemed like things got a little wonky when doing stuff with the torch in the off hand. Great mod, btw, it's the best one like it I've found.

**Comment by realguyman** [comment]
This issue has been fixed in 0.9.1.
